[book]
title = "Write Your First Compiler In C With Libchibi"
authors = ["Olija Downing"]
language = "en"

[output.html]
default-theme = "dark"
preferred-dark-theme = "Coal"
additional-css = ["theme/highlight.css"]
